<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Resources\09-This PC.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="F23.StringSimilarity" Version="6.0.0" />
		<PackageReference Include="FuzzySharp" Version="2.0.2" />
		<PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
		<PackageReference Include="Selenium.Support" Version="4.35.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.35.0" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="C:\Users\ITTEAM\Desktop\Personal Projects\UmatoMusume\.editorconfig" />
		<None Include="UmamusumePD.sqlite" CopyToOutputDirectory="PreserveNewest" />
		<None Include="Assets\**" CopyToOutputDirectory="PreserveNewest" />
		<None Include="Extras\**" CopyToOutputDirectory="PreserveNewest" />
		<None Include="version_control.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="restart.bat" CopyToOutputDirectory="PreserveNewest" />
		<None Include="config.txt" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\09-This PC.ico" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="PaddleOCRJson">
			<HintPath>References\PaddleOCRJson.NET\PaddleOCRJson.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extras\ChromeProfile\AmountExtractionHeuristicRegexes\" />
		<Folder Include="Extras\ChromeProfile\AutofillStates\" />
		<Folder Include="Extras\ChromeProfile\CookieReadinessList\" />
		<Folder Include="Extras\ChromeProfile\Crashpad\attachments\" />
		<Folder Include="Extras\ChromeProfile\Crashpad\reports\" />
		<Folder Include="Extras\ChromeProfile\Crowd Deny\" />
		<Folder Include="Extras\ChromeProfile\Default\blob_storage\23d89c36-199c-4c31-a342-9209323e7269\" />
		<Folder Include="Extras\ChromeProfile\Default\Download Service\Files\" />
		<Folder Include="Extras\ChromeProfile\FileTypePolicies\" />
		<Folder Include="Extras\ChromeProfile\Fingerprinting Protection Filter\Unindexed Rules\" />
		<Folder Include="Extras\ChromeProfile\FirstPartySetsPreloaded\" />
		<Folder Include="Extras\ChromeProfile\HistorySearch\" />
		<Folder Include="Extras\ChromeProfile\hyphen-data\" />
		<Folder Include="Extras\ChromeProfile\MaskedDomainListPreloaded\" />
		<Folder Include="Extras\ChromeProfile\MEIPreload\" />
		<Folder Include="Extras\ChromeProfile\OnDeviceHeadSuggestModel\" />
		<Folder Include="Extras\ChromeProfile\OpenCookieDatabase\" />
		<Folder Include="Extras\ChromeProfile\OptimizationHints\" />
		<Folder Include="Extras\ChromeProfile\OriginTrials\" />
		<Folder Include="Extras\ChromeProfile\PKIMetadata\" />
		<Folder Include="Extras\ChromeProfile\PlusAddressBlocklist\" />
		<Folder Include="Extras\ChromeProfile\PrivacySandboxAttestationsPreloaded\" />
		<Folder Include="Extras\ChromeProfile\ProbabilisticRevealTokenRegistry\" />
		<Folder Include="Extras\ChromeProfile\SafetyTips\" />
		<Folder Include="Extras\ChromeProfile\SSLErrorAssistant\" />
		<Folder Include="Extras\ChromeProfile\TpcdMetadata\" />
		<Folder Include="Extras\ChromeProfile\TrustTokenKeyCommitments\" />
		<Folder Include="Extras\ChromeProfile\WasmTtsEngine\" />
		<Folder Include="Extras\ChromeProfile\WidevineCdm\" />
		<Folder Include="Extras\ChromeProfile\ZxcvbnData\" />
	</ItemGroup>

	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Users\ITTEAM\Desktop\Personal Projects\UmatoMusume\.editorconfig" />
	</ItemGroup>
</Project>
